version: '3.8'

services:
  tasks-api:
    image: tasks-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - local-db
      - redis-stack
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=local-db;Database=localdefaultdb;Username=appuser;Password=password123
      - Seq__ServerUrl=http://seq-logging:5341
      - Redis__Server=redis-stack:6379
      - Redis__InstanceName=TasksApi
  local-db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=localdefaultdb
    networks:
      - default
    ports:
      - "5432:5432"
  local-db-migrations:
    image: flyway/flyway:latest
    volumes:
      - ./db/sql:/flyway/sql
      - ./db/config:/flyway/conf
    command: migrate -connectRetries=20
    depends_on:
      - local-db
    networks:
      - default
    environment:
      FLYWAY_EDITION: community
      FLYWAY_CONFIG_FILES: /flyway/conf/flyway.conf
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
  seq-logging:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - default
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - default
networks:
  default:
    name: tasks-api
volumes:
  localdbdata: