name: Feature
description: New use case or business requirement
labels: ["feature", "p3-normal"]
body:
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What should the user be able to do?
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ]
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain
      options: [api, domain, persistence, caching, observability, infra]
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [p1-critical, p2-high, p3-normal]
      default: 2
    validations:
      required: true
