CREATE TABLE events (
    id UUID PRIMARY KEY NOT NULL UNIQUE,
    aggregate_id UUID NOT NULL,
    version INT NOT NULL,
    type VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    data JSON NOT NULL
);